"""Bridge to agentbastion / bastiongate: turn flagged memory into a guard policy.

Emits a memory policy the firewall can enforce — quarantine (strip on load) the
poisoned entries so they never reach the model's context again. Closes the loop the
same way the sibling tools' `harden` do.
"""

from __future__ import annotations

from .models import ScanReport


def to_policy_yaml(report: ScanReport) -> str:
    flagged = report.sorted_findings()
    verdict = "allow" if report.verdict == "allow" else "quarantine"
    lines = [
        "# agentbastion / bastiongate memory policy generated by bastionmemory",
        f"# target: {report.target}  verdict={report.verdict}",
        "memory:",
        f"  default: {verdict}",
    ]
    if flagged:
        lines.append("  quarantine_entries:  # strip these before loading memory into context")
        for f in flagged:
            reason = f"{f.check}" + (f"/{f.temporal}" if f.temporal else "")
            lines.append(f"    - file: {_q(f.file)}")
            lines.append(f"      line: {f.line}")
            lines.append(f"      reason: {reason}")
            lines.append(f"      text: {_q(f.evidence)}")
    return "\n".join(lines) + "\n"


def _q(s: str) -> str:
    if s and all(c.isalnum() or c in "_-./ " for c in s):
        return s
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
